// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateItem(ctx context.Context, arg CreateItemParams) (Item, error)
	CreateSale(ctx context.Context, arg CreateSaleParams) (Sale, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CurrentWeekSales(ctx context.Context, userID uuid.UUID) (int32, error)
	DeleteItem(ctx context.Context, arg DeleteItemParams) error
	DeleteSale(ctx context.Context, arg DeleteSaleParams) error
	GetInventoryStats(ctx context.Context, userID uuid.UUID) (GetInventoryStatsRow, error)
	GetItem(ctx context.Context, id uuid.UUID) (Item, error)
	GetItemForUpdate(ctx context.Context, id uuid.UUID) (Item, error)
	GetSale(ctx context.Context, arg GetSaleParams) (Sale, error)
	GetSaleForUpdate(ctx context.Context, arg GetSaleForUpdateParams) (Sale, error)
	GetUser(ctx context.Context, email string) (User, error)
	LastWeekSales(ctx context.Context, userID uuid.UUID) (int32, error)
	ListItems(ctx context.Context, userID uuid.UUID) ([]Item, error)
	ListSales(ctx context.Context, arg ListSalesParams) ([]ListSalesRow, error)
	ListSalesByUserId(ctx context.Context, userID uuid.UUID) ([]ListSalesByUserIdRow, error)
	ListUsers(ctx context.Context) ([]User, error)
	PriceSoldByDate(ctx context.Context, userID uuid.UUID) ([]PriceSoldByDateRow, error)
	PriceSoldByWeek(ctx context.Context, userID uuid.UUID) ([]PriceSoldByWeekRow, error)
	UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error)
	UpdateItemQuantity(ctx context.Context, arg UpdateItemQuantityParams) (Item, error)
	UpdateSale(ctx context.Context, arg UpdateSaleParams) (Sale, error)
}

var _ Querier = (*Queries)(nil)
