import './globals.css';
import { Balsamiq_Sans } from 'next/font/google';
import Navbar from './navbar';
import { QueryClientWrapper } from './query-client';

const balsamiq = Balsamiq_Sans({
    weight: ['400', '700'],
    subsets: ['latin'],
    variable: '--font-balsamiq',
});

export const metadata = {
    title: 'Copia',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='en'>
            <body className={`${balsamiq.variable} font-balsamiq`}>
                <QueryClientWrapper>
                    <Navbar />
                    <main className='min-h-screen py-20'>{children}</main>
                </QueryClientWrapper>
            </body>
        </html>
    );
}
