// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateItem(ctx context.Context, arg CreateItemParams) (Item, error)
	DeleteItem(ctx context.Context, id uuid.UUID) error
	GetItem(ctx context.Context, id uuid.UUID) (Item, error)
	GetItemForUpdate(ctx context.Context, id uuid.UUID) (Item, error)
	ListItems(ctx context.Context, arg ListItemsParams) ([]Item, error)
	UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error)
}

var _ Querier = (*Queries)(nil)
