// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateItem(ctx context.Context, arg CreateItemParams) (Item, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteItem(ctx context.Context, arg DeleteItemParams) error
	GetItem(ctx context.Context, id uuid.UUID) (Item, error)
	GetItemForUpdate(ctx context.Context, id uuid.UUID) (Item, error)
	GetUser(ctx context.Context, email string) (User, error)
	ListItems(ctx context.Context, userID uuid.UUID) ([]Item, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error)
}

var _ Querier = (*Queries)(nil)
